import type { RegistrationRole } from '@/lib/api';

export function isAutoGeneratedUsername(username?: string | null): boolean {
  return Boolean(username && /^user_[0-9a-f]{8}$/i.test(username));
}

export function hasChosenRegistrationRole(
  user?: { role?: string; username?: string | null } | null,
): user is { role: RegistrationRole; username?: string } {
  if (!user || isAutoGeneratedUsername(user.username)) return false;
  return user.role === 'client' || user.role === 'freelancer';
}

export function needsProfileSetup(
  user?: { role?: string; username?: string | null } | null,
): boolean {
  return Boolean(user && !hasChosenRegistrationRole(user));
}
