import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import {
  checkUserExists,
  fetchUserProfile,
  registerUser,
  updateUserProfile,
  type RegistrationRole,
  type UserProfile,
} from '@/lib/api';
import {
  hasChosenRegistrationRole,
  isAutoGeneratedUsername,
} from '@/lib/utils/profile';
import { useArbitratorAccess } from '@/hooks/useArbitratorAccess';
import { useReputation } from '@/hooks/useReputation';
import { ReputationBadge } from '@/components/shared/ReputationBadge';
import { BlockiesAvatar } from '@/components/shared/BlockiesAvatar';
import { truncateAddress } from '@/lib/utils/address';
import { ArbitratorOnboardingPanel } from '@/components/profile/ArbitratorOnboardingPanel';

export function ProfilePage() {
  const { address, user, isAuthenticated, walletSessionNotice, signIn, loading: authLoading, refreshSession } = useAuth();
  const arbitrator = useArbitratorAccess();
  const { reputation, loading: reputationLoading } = useReputation(address);
  const location = useLocation();
  const state = location.state as {
    needRole?: RegistrationRole;
    needArbitratorStake?: boolean;
  } | null;

  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [username, setUsername] = useState('');
  const [fullName, setFullName] = useState('');
  const [role, setRole] = useState<RegistrationRole | ''>('');
  const [skills, setSkills] = useState('');
  const [, setExists] = useState<boolean | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const displayUsername = profile?.username ?? user?.username;
  const registrationComplete = hasChosenRegistrationRole({
    username: displayUsername,
    role: profile?.role ?? user?.role,
  });
  const needsUsername = isAutoGeneratedUsername(displayUsername);

  const applyUserToForm = (u: UserProfile) => {
    setProfile(u);
    setUsername(u.username || '');
    setFullName(u.profile?.fullName || '');
    const r = u.role;
    if (r === 'client' || r === 'freelancer') setRole(r);
    else setRole('');
    setSkills((u.profile?.skills || []).join(', '));
  };

  const loadProfileForAddress = async (wallet: string) => {
    const res = await checkUserExists(wallet);
    setExists(res.exists);
    if (res.exists && res.user) {
      applyUserToForm(res.user as UserProfile);
      return;
    }
    if (res.exists) {
      const profileRes = await fetchUserProfile(wallet);
      if (profileRes.success) {
        applyUserToForm(profileRes.user);
      }
    } else {
      setProfile(null);
      setUsername('');
      setRole('');
    }
  };

  useEffect(() => {
    if (!address) {
      setExists(null);
      setProfile(null);
      return;
    }
    let cancelled = false;
    setError(null);

    loadProfileForAddress(address)
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to load profile');
      });

    return () => {
      cancelled = true;
    };
  }, [address, isAuthenticated, user?.walletAddress, user?.username, user?.role]);

  const handleRegister = async () => {
    if (!address) return;
    const trimmedUsername = username.trim();
    if (needsUsername && !trimmedUsername) return;
    if (role !== 'client' && role !== 'freelancer') {
      setError('Choose Client or Freelancer before continuing.');
      return;
    }
    if (needsUsername && isAutoGeneratedUsername(trimmedUsername)) {
      setError('Pick a permanent username (not the temporary user_xxxxxxxx name).');
      return;
    }
    setLoading(true);
    setError(null);
    setMessage(null);
    try {
      const res = needsUsername
        ? await registerUser({
            walletAddress: address,
            username: trimmedUsername,
            role,
          })
        : await updateUserProfile({ role });
      if (res.success && res.user) {
        applyUserToForm(res.user);
        setExists(true);
        await refreshSession();
        if (needsUsername) {
          await loadProfileForAddress(address);
        }
        setMessage('Registration complete. You can update your profile below anytime.');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  const handleUpdate = async () => {
    setLoading(true);
    setError(null);
    setMessage(null);
    try {
      const res = await updateUserProfile({
        fullName: fullName.trim() || undefined,
        role: role === 'client' || role === 'freelancer' ? role : undefined,
        skills: skills
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean),
      });
      if (res.success && res.user) {
        setProfile(res.user);
        if (res.user.role === 'client' || res.user.role === 'freelancer') {
          setRole(res.user.role);
        }
        await refreshSession();
        setMessage('Profile updated.');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Update failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="page">
      <div className="page-header">
        <h2>Profile</h2>
        <p className="muted">
          Sign in with SIWE, pick a username and choose <strong>Client</strong> or{' '}
          <strong>Freelancer</strong> on first login. Arbitrator access requires on-chain stake (min 50
          USDC), not a profile role.
        </p>
      </div>

      {state?.needRole && !registrationComplete && (
        <p className="error banner">
          Complete registration: choose <strong>{state.needRole}</strong> (or your preferred role) below.
        </p>
      )}
      {state?.needArbitratorStake && !arbitrator.loading && !arbitrator.isValid && (
        <p className="error banner">
          Arbitrator console requires at least 50 USDC staked via PlatformTreasury (or membership in the
          arbitrator pool). Stake on-chain, then refresh.
        </p>
      )}

      {address && (
        <header className="profile-header panel">
          <BlockiesAvatar address={address} size={56} />
          <div className="profile-header-meta">
            <h2 className="profile-username">{displayUsername ?? 'Anonymous'}</h2>
            <p className="mono profile-wallet" title={address}>
              {truncateAddress(address, 6, 4)}
            </p>
            {registrationComplete && user?.role && (
              <span className="badge role-badge">{user.role}</span>
            )}
            <p className="muted profile-joined">FAPEX member · Sepolia testnet</p>
          </div>
        </header>
      )}

      {address && (
        <section className="panel profile-arbitrator-card">
          <h3>Arbitrator</h3>
          <p className="muted phase-note">
            On-chain reputation and stake status for dispute panel eligibility.
          </p>
          <ReputationBadge reputation={reputation} loading={reputationLoading} />
          {!arbitrator.loading && arbitrator.stakedAmount != null && (
            <div className="arbitrator-stake-summary">
              <p>
                <strong>{arbitrator.stakedAmount} USDC</strong> staked
                {arbitrator.minStake != null && ` (min ${arbitrator.minStake})`}
              </p>
              <p className={arbitrator.isValid ? 'success' : 'error'}>
                {arbitrator.isValid
                  ? arbitrator.inPool
                    ? 'In arbitrator pool — eligible for assignments'
                    : 'Stake sufficient — join pool to receive assignments'
                  : `Stake at least ${arbitrator.minStake ?? 50} USDC for console access`}
              </p>
              {arbitrator.message && <p className="muted">{arbitrator.message}</p>}
            </div>
          )}
          {arbitrator.loading && <p className="muted">Checking on-chain stake…</p>}
        </section>
      )}

      {address && <ArbitratorOnboardingPanel />}

      {!address && <p className="muted">Connect your wallet to manage your profile.</p>}
      {address && !isAuthenticated && (
        <section className="panel form-panel">
          <p className="muted">Sign in with SIWE before registering or updating your profile.</p>
          <button className="btn primary" type="button" onClick={signIn} disabled={authLoading}>
            {authLoading ? 'Signing…' : 'Sign in (SIWE)'}
          </button>
        </section>
      )}

      {walletSessionNotice && (
        <p className="muted banner info">{walletSessionNotice}</p>
      )}

      {address &&
        isAuthenticated &&
        user?.walletAddress?.toLowerCase() === address.toLowerCase() &&
        !registrationComplete && (
        <section className="panel form-panel">
          <h3>{needsUsername ? 'Complete registration' : 'Choose your role'}</h3>
          {needsUsername && (
            <p className="muted">
              SIWE sign-in created a temporary username ({displayUsername}). Pick a permanent username and
              your role.
            </p>
          )}
          {needsUsername && (
            <label className="field">
              Username
              <input className="input" value={username} onChange={(e) => setUsername(e.target.value)} />
            </label>
          )}
          <fieldset className="field">
            <legend>I am a…</legend>
            <div className="roles-grid">
              <label className={`role-card ${role === 'client' ? 'selected' : ''}`}>
                <input
                  type="radio"
                  name="registration-role"
                  value="client"
                  checked={role === 'client'}
                  onChange={() => setRole('client')}
                />
                <h3>Client</h3>
                <p>Post jobs and fund escrow</p>
              </label>
              <label className={`role-card ${role === 'freelancer' ? 'selected' : ''}`}>
                <input
                  type="radio"
                  name="registration-role"
                  value="freelancer"
                  checked={role === 'freelancer'}
                  onChange={() => setRole('freelancer')}
                />
                <h3>Freelancer</h3>
                <p>Browse jobs and submit bids</p>
              </label>
            </div>
          </fieldset>
          <button
            className="btn primary"
            type="button"
            onClick={handleRegister}
            disabled={
              loading ||
              (needsUsername &&
                (!username.trim() || isAutoGeneratedUsername(username.trim())))
            }
          >
            {needsUsername ? 'Save username & role' : 'Save role'}
          </button>
        </section>
      )}

      {address && isAuthenticated && registrationComplete && (
        <section className="panel form-panel">
          <h3>{profile?.username || user?.username || 'Your profile'}</h3>
          <label className="field">
            Display name
            <input className="input" value={fullName} onChange={(e) => setFullName(e.target.value)} />
          </label>
          <label className="field">
            Registration role
            <select
              className="input"
              value={role}
              onChange={(e) => setRole(e.target.value as RegistrationRole)}
            >
              <option value="client">Client — post jobs, fund escrow</option>
              <option value="freelancer">Freelancer — browse jobs, submit bids</option>
            </select>
          </label>
          <label className="field">
            Skills (comma-separated)
            <input className="input" value={skills} onChange={(e) => setSkills(e.target.value)} />
          </label>
          <button className="btn primary" type="button" onClick={handleUpdate} disabled={loading}>
            Save profile
          </button>
        </section>
      )}

      {message && <p className="badge success">{message}</p>}
      {error && <p className="error">{error}</p>}
    </main>
  );
}
