import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import {
  checkUserExists,
  fetchUserProfile,
  registerUser,
  updateUserProfile,
  type RegistrationRole,
  type UserProfile,
} from '@/lib/api';

function isAutoGeneratedUsername(username?: string | null): boolean {
  return Boolean(username && /^user_[0-9a-f]{8}$/i.test(username));
}

export function ProfilePage() {
  const { address, isAuthenticated, user, signIn, loading: authLoading, refreshSession } = useAuth();
  const location = useLocation();
  const state = location.state as {
    needRole?: RegistrationRole;
    needArbitratorStake?: boolean;
  } | null;

  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [username, setUsername] = useState('');
  const [fullName, setFullName] = useState('');
  const [role, setRole] = useState<RegistrationRole>('freelancer');
  const [skills, setSkills] = useState('');
  const [exists, setExists] = useState<boolean | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const loadProfileForAddress = async (wallet: string) => {
    const res = await checkUserExists(wallet);
    setExists(res.exists);
    if (res.exists && res.user) {
      setProfile(res.user as UserProfile);
      setUsername(res.user.username || '');
      setFullName(res.user.profile?.fullName || '');
      const r = res.user.role;
      if (r === 'client' || r === 'freelancer') setRole(r);
      setSkills((res.user.profile?.skills || []).join(', '));
      return;
    }
    if (res.exists) {
      const profileRes = await fetchUserProfile(wallet);
      if (profileRes.success) {
        setProfile(profileRes.user);
        setUsername(profileRes.user.username || '');
        setFullName(profileRes.user.profile?.fullName || '');
        const r = profileRes.user.role;
        if (r === 'client' || r === 'freelancer') setRole(r);
        setSkills((profileRes.user.profile?.skills || []).join(', '));
      }
    } else {
      setProfile(null);
      setUsername('');
    }
  };

  useEffect(() => {
    if (!address) {
      setExists(null);
      setProfile(null);
      return;
    }
    let cancelled = false;
    setError(null);

    loadProfileForAddress(address)
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to load profile');
      });

    return () => {
      cancelled = true;
    };
  }, [address, isAuthenticated, user?.walletAddress]);

  useEffect(() => {
    if (user?.role === 'client' || user?.role === 'freelancer') {
      setRole(user.role);
    }
  }, [user?.role]);

  const handleRegister = async () => {
    if (!address || !username.trim()) return;
    setLoading(true);
    setError(null);
    setMessage(null);
    try {
      const res = await registerUser({ walletAddress: address, username: username.trim() });
      if (res.success) {
        setExists(true);
        await refreshSession();
        await loadProfileForAddress(address);
        setMessage('Username saved. Choose Client or Freelancer and save your profile below.');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  const handleUpdate = async () => {
    setLoading(true);
    setError(null);
    setMessage(null);
    try {
      const res = await updateUserProfile({
        fullName: fullName.trim() || undefined,
        role,
        skills: skills
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean),
      });
      if (res.success && res.user) {
        setProfile(res.user);
        await refreshSession();
        setMessage('Profile updated.');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Update failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="page">
      <div className="page-header">
        <h2>Profile</h2>
        <p className="muted">
          Sign in with SIWE, register a username, then pick <strong>Client</strong> or{' '}
          <strong>Freelancer</strong>. Arbitrator access requires on-chain stake (min 50 USDC), not a
          profile role.
        </p>
      </div>

      {state?.needRole && (
        <p className="error banner">
          This page requires the <strong>{state.needRole}</strong> role. Update your role below and save.
        </p>
      )}
      {state?.needArbitratorStake && (
        <p className="error banner">
          Arbitrator console requires at least 50 USDC staked via PlatformTreasury. Stake on-chain, then
          refresh.
        </p>
      )}

      {!address && <p className="muted">Connect your wallet to manage your profile.</p>}
      {address && !isAuthenticated && (
        <section className="panel form-panel">
          <p className="muted">Sign in with SIWE before registering or updating your profile.</p>
          <button className="btn primary" type="button" onClick={signIn} disabled={authLoading}>
            {authLoading ? 'Signing…' : 'Sign in (SIWE)'}
          </button>
        </section>
      )}

      {address && isAuthenticated && user?.walletAddress?.toLowerCase() !== address.toLowerCase() && (
        <p className="error banner">
          Connected wallet ({address}) differs from signed-in session ({user?.walletAddress}). Sign out and
          sign in again.
        </p>
      )}

      {address &&
        isAuthenticated &&
        user?.walletAddress?.toLowerCase() === address.toLowerCase() &&
        (exists === false || isAutoGeneratedUsername(profile?.username ?? user?.username)) && (
        <section className="panel form-panel">
          <h3>{exists ? 'Choose username' : 'Register'}</h3>
          {exists && (
            <p className="muted">
              SIWE sign-in created a temporary username ({profile?.username || user?.username}). Pick a
              permanent username below.
            </p>
          )}
          <label className="field">
            Username
            <input className="input" value={username} onChange={(e) => setUsername(e.target.value)} />
          </label>
          <button className="btn primary" type="button" onClick={handleRegister} disabled={loading}>
            {exists ? 'Save username' : 'Register'}
          </button>
        </section>
      )}

      {address &&
        isAuthenticated &&
        exists !== false &&
        !isAutoGeneratedUsername(profile?.username ?? user?.username) && (
        <section className="panel form-panel">
          <h3>{profile?.username || user?.username || 'Your profile'}</h3>
          <label className="field">
            Display name
            <input className="input" value={fullName} onChange={(e) => setFullName(e.target.value)} />
          </label>
          <label className="field">
            Registration role
            <select
              className="input"
              value={role}
              onChange={(e) => setRole(e.target.value as RegistrationRole)}
            >
              <option value="client">Client — post jobs, fund escrow</option>
              <option value="freelancer">Freelancer — browse jobs, submit bids</option>
            </select>
          </label>
          <label className="field">
            Skills (comma-separated)
            <input className="input" value={skills} onChange={(e) => setSkills(e.target.value)} />
          </label>
          <button className="btn primary" type="button" onClick={handleUpdate} disabled={loading}>
            Save profile
          </button>
        </section>
      )}

      {message && <p className="badge success">{message}</p>}
      {error && <p className="error">{error}</p>}
    </main>
  );
}
